### ISSUE TITLE
RASTtk 1.30 has hard-coded paths to Olson's home directory 

### ISSUE THREAD

**Issue by mmp3** [TheSEED/RASTtk-Distribution#11]
Following the installation instruction for v1.3.0:

```
sudo dpkg -i rasttk-v1.3.0.deb
sudo apt-get install -f
```

results in files that have hard-coded paths to Olson's machine.

`$ vi /usr/bin/rast-create-genome`

```
#!/bin/sh
export KB_TOP=/usr/share/rasttk/deployment
export KB_RUNTIME=/home/olson/KB/runtime/
export PATH=/home/olson/KB/runtime//bin:/usr/share/rasttk/deployment/bin:$PATH
export PERL5LIB=/usr/share/rasttk/deployment/lib
/home/olson/KB/runtime//bin/perl /usr/share/rasttk/deployment/plbin/rast-create-genome.pl "$@"
```

**Comment by olsonanl** [comment]
Yes, there were issues with the linux releases. The latest RASTtk is available in the PATRIC command line interface releases at 

https://github.com/PATRIC3/PATRIC-distribution/releases

--bob
