### ISSUE TITLE
Return code from rast-process-genome-batch: 255malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /disks/kb/deployment/plbin/rast-process-genome-batch.pl line 115, <$fh> chunk 1.

### ISSUE THREAD

**Issue by ddjamalova** [TheSEED/RASTtk-Distribution#13]
Hi,
rasttk doesn't work in batch mode. I've got the error:

Return code from rast-process-genome-batch: 255malformed JSON string, neither tag, array, object, number, string or atom, at character offset 0 (before "(end of string)") at /disks/kb/deployment/plbin/rast-process-genome-batch.pl line 115, <$fh> chunk 1.

But rast-process-genome on single genomes works properly. Is it server error?

**Comment by olsonanl** [comment]
There is an issue with authentication to the file service I need to check on.

However, the more supported mechanism for batch processing is via the PATRIC command line. PATRIC is the NIAID bioinformatics resource that is funding the latest genome annotation effort.

This tutorial discusses the command line tools, using the assembly tool as an example. You can submit genome annotations using p3-submit-genome-annotation:

https://docs.patricbrc.org/cli_tutorial/cli_services.html

This tutorial discusses the installation f the CLI; it is similar to the mechanism for RASTtk (it is derived from the RASTtk work and in fact includes the RASTtk distribution as part of it).

https://docs.patricbrc.org/cli_tutorial/index.html


Bob


________________________________
