### ISSUE TITLE
Rasttk

### ISSUE THREAD

**Issue by scubapenn** [TheSEED/RASTtk-Distribution#16]
Just tried to run rasttk and got this error:
 echo "kb|g.0" | genomes_to_contigs | contigs_to_sequences  > E_coli.contig   
/Applications/RASTtk.app/deployment/bin/genomes_to_contigs: line 9: /Applications/RASTtk.app/runtime/bin/perl: Bad CPU type in executable
/Applications/RASTtk.app/deployment/bin/contigs_to_sequences: line 9: /Applications/RASTtk.app/runtime/bin/perl: Bad CPU type in executable

**Comment by olsonanl** [comment]
What machine type and OS are you running on?

The RASTtk.app distribution is quite old and not supported. You can try the newer releases of the PATRIC CLI runtime which include the rasttk tooling:

https://github.com/PATRIC3/PATRIC-distribution

Bob

**Comment by YuLanSky** [comment]
I have the same problem, with RASTtk Release 1.3.0, No matter what I do, I will get a response: /Applications/RASTtk.app/deployment/bin/rast-create-genome: line 9: /Applications/RASTtk.app/runtime/bin/perl: Bad CPU type in executable
My computer is MacBook Pro (15-inch, 2017, Intel Core i7)

**Comment by olsonanl** [comment]
Yes, you will have problems with that version. Please try the newer PATRIC CLI that includes the rasttk tooling: 

https://github.com/PATRIC3/PATRIC-distribution

Bob
